tilequeue/command.py
```
tilequeue/command.py
-This will make it obvious that the user needs to supply a
`--config` path, and produce a human error message when the file
isn't found (you otherwise get a rather ugly and unenlightening
trace).
```
=> make --config required, and check config path

config.yaml.sample, tilequeue/command.py, tilequeue/config.py
Increase seeding configurability by:
* allowing users to filter metro-extracts by city name
* adding the ability to specify any number of custom bounding boxes
=> add option to seed custom bounding-boxes and filter metro-extracts

tilequeue/command.py, tilequeue/transform.py
This PR fixes seams on tile borders, and is analogous to [this TileStache PR](https://github.com/mapzen/TileStache/pull/34). Note that you'll need to run:
```
pip install --upgrade git+https://github.com/mapzen/TileStache@remove-tile-seams
```
in order to pull in the necessary changes concerning the TileStache config.
related PRs: mapzen/vector-datasource#104, mapzen/TileStache#34
=> fix seams on tile borders

tilequeue/command.py, tilequeue/process.py, tilequeue/worker.py
This adds a post-processing step which comes after the functions for transforming and sorting the individual layers. The post-processing step has access to the whole tile, and so it can modify existing layers or create new layers based on existing layers. This allows us to "intercut" one layer with another, see https://github.com/mapzen/TileStache/pull/37, or create layers based purely on already-queried data (e.g: centroids).
Note: this is part of trying to solve https://github.com/mapzen/vector-datasource/issues/136.
=> Add framework to post-process layers

tilequeue/process.py
Fix bug where post-processing would only replace existing layers, not add new ones, which we need for mapzen/vector-datasource#140.
=> Allow post-processing to append new layers.

tilequeue/process.py
We want to not compute water boundaries for mapzen/vector-datasource#203, so the post-processor needs to know what the zoom is to switch itself off.
=> Pass zoom parameter to the post-processing functions.

tilequeue/command.py, tilequeue/query.py
Added bbox_intersection filter for Jinja, which allows clipping to the query bounding box. Although doing an intersection operation in the database rather than on the client can take some time, it seems it's worthwhile in this case to avoid sending too much over the network.
Connects to mapzen/vector-datasource#302.
=> Added bbox_intersection filter for Jinja.

tilequeue/wof.py
The assumption here is that the header indexes would change more often than the names. This should help keep the parsing logic more resilient in the case when a new column is added.
=> Parse WOF neighbourhoods using header names

tilequeue/wof.py
When the label position is missing. This isn't ideal, but the geometry position will suffice until the record is fixed.
The previous code would error if the label position was missing and, while missing the label position isn't great, it can be recovered from. The error, on the other hand, causes alerts, which is a bit extreme.
@nvkelso could you review, please?
=> Fall back to using the geometry position

circle.yml, setup.py, tests/test_wof_http.py, tilequeue/command.py, tilequeue/wof.py
Adds a configuration parameter for the number of retries to attempt when HTTP connections fail or return one of the whitelisted error status codes.
Connects to #60.
@nvkelso could you review, please?
=> Be robust to HTTP errors

tests/test_store.py, tilequeue/store.py
This eliminates the extra slash from the s3 path. I don't think that this would make any difference, because it seems like the objects were still being saved in the correct location regardless. But this change probably makes sense to make anyway.
=> Correct the s3 tile key path

tilequeue/command.py
Use an empty list if the 'transforms' parameter is missing, rather than raise KeyError.
Connects to mapzen/vector-datasource#537.
=> Allow transforms list to be optional

tests/test_transform.py
Connects to https://github.com/mapzen/vector-datasource/issues/546
@nvkelso could you review please?
=> Add road sort key tests

tilequeue/process.py
Don't simplify / remove small features at zoom 16, as this is now the zoom which contains everything needed for cutting higher level zoom tiles.
Connects to mapzen/vector-datasource#557.
=> Fix missing small buildings at z16

tests/test_store.py, tilequeue/format/__init__.py, tilequeue/format/geojson.py, tilequeue/transform.py
Connects to https://github.com/mapzen/vector-datasource/issues/698
Instead of using a custom json encoder to truncate precision, use the python `round` function.
I also added in other optimizations:
* avoid unnecessary serialization/deserialization to/from wkb for json and mvt.
* for json, instead of serializing and deserializing each layer and then serializing them all again, just make the appropriate structure and serialize once
=> Update json encoding to handle invalid geometries

tilequeue/command.py, tilequeue/process.py
Connects to https://github.com/mapzen/vector-datasource/issues/202
Adds support for a configurable area threshold value in pixels. This is a per layer value that will be applied to all polygonal features. Any feature whose area is less than this value will be dropped from tiles.
=> Support configurable area thresholds

tests/test_buffer.py, tilequeue/command.py, tilequeue/config.py, tilequeue/format/__init__.py, tilequeue/process.py, tilequeue/query.py, tilequeue/tile.py, tilequeue/transform.py, tilequeue/worker.py
Connects to https://github.com/mapzen/vector-datasource/issues/106
The bounding box that the queries used is buffered to be the max of any of the buffer sizes configured across all formats. This trade-off allowed us to still use a single bounding box in the queries to keep things simpler for now. We could be more precise here, but we would need to update all queries to use the corresponding bounding box to match the geometry type.
Another potential performance issue is that the buffered bounds are calculated from the config per feature now, because the geometry type is a factor. This could be made faster if need be.
There are also some tileserver updates that are required. I'll put in a pr for that once the tilequeue changes are nailed down. There will also be updates necessary to the …
=> Add configurable buffer support

tilequeue/process.py
For consistency, keep json property strings encoded in utf8.
=> Ensure json properties are utf8 encoded

tests/test_buffer.py, tilequeue/command.py, tilequeue/config.py, tilequeue/process.py, tilequeue/tile.py, tilequeue/transform.py
Connects to https://github.com/mapzen/vector-datasource/issues/106
Depends on https://github.com/mapzen/vector-datasource/pull/870
The query or `padded_bounds` are now a dict with 3 bounds keyed off of
geometry type.
=> Discriminate query bounds on geometry type

logging.conf.sample, tilequeue/process.py, tilequeue/query.py, tilequeue/worker.py
This will allow us to collect statistics about which layers contribute most to network traffic, and may help us optimise queries which are returning too much data.
=> Add basic size logging for the objects returned from queries.

tilequeue/format/__init__.py
Connects to https://github.com/tilezen/vector-datasource/issues/106
The previous code seemed like it would override the mvt format that got stored with the buffered format because the extension was the same. That seems odd because I thought we had checked the .mvtb extension, but maybe not?
@nvkelso, @zerebubuth could you review please?
=> Correct the buffered mvt format

config.yaml.sample, tests/test_metatile.py, tilequeue/command.py, tilequeue/config.py, tilequeue/format/__init__.py, tilequeue/metatile.py, tilequeue/worker.py
If configured (`metatile size` is not `None`), this will write metatiles to storage rather than individual tiles. Each metatile is a zip file containing multiple formats, compatible with [Tapalcatl](https://github.com/tilezen/tapalcatl). Space for future extensions to multiple coordinates has been left, but isn't supported in this change.
I couldn't find anywhere that support for _reading_ metatiles is required in tilequeue at the moment. Is that only needed in tileserver?
@rmarianski, @iandees could you review, please?
=> Add support for writing metatiles

config.yaml.sample, tests/queue/test_multisqs.py, tests/test_command.py, tilequeue/command.py, tilequeue/config.py, tilequeue/queue/__init__.py, tilequeue/queue/multisqs.py, tilequeue/queue/sqs.py, tilequeue/tile.py, tilequeue/worker.py
Connects to https://github.com/tilezen/tilequeue/issues/18
=> Add priority queue implementation

config.yaml.sample, tilequeue/command.py, tilequeue/config.py, tilequeue/worker.py
Added a configuration setting to allow the storage of the original format files in addition to the metatile. This can allow a 'graceful' switch between a non-metatiled configuration and one using metatiles.
@iandees could you review, please?
=> Allow storing original file formats in addition to metatile zips

tests/test_metatile.py, tilequeue/metatile.py
This isn't needed in tilequeue itself, but is needed in tileserver. However, it is useful to have here along with the rest of the metatile functions to keep that related functionality all in one place.
@iandees could you review, please?
=> Add function to read data from a metatile.

tests/test_command.py, tilequeue/command.py
Coordinate zooms can sometimes be of type `long` rather than `int` if they are unmarshalled from a `long` integer. This adds `long` to the acceptable types list, and adds a test for that case.
This was causing assertion errors on the background thread in dev.
@iandees could you review, please?
=> Support long zooms

tilequeue/format/topojson.py
Connects to https://github.com/tilezen/vector-datasource/issues/1145
Bumping the scale makes the rendering artifact go away. We'll likely want to revisit the topojson format again with an eye towards returning ogc valid geometries, but this is a quick fix that seems to    help. The downside here is that it may increase the topojson format size across the board for complex geometries.
=> Increase topojson scale from 1024 -> 4096

tilequeue/format/mvt.py
Use the built-in Python rounding function instead of the `Decimal` one.
=> Use round_fn to specify built-in round function for MVT

tilequeue/command.py, tilequeue/postgresql.py, tilequeue/query.py
Connects to https://github.com/tilezen/tilequeue/issues/141
Simplify our code a bit by using psycopg2's built-in connection pools.
=> Use psycopg2 connection pools

tests/test_tile.py, tilequeue/tile.py
More than two coordinates are allowed by the GeoJSON spec, and this was causing some errors in the WOF import logs because the reprojection function assumed that there were only two. This fixes it by allowing any number of extra coordinates, which are all ignored.
@rmarianski, @iandees please could you review?
=> Ignore extra coordinates, e.g: z, in reprojection.

tilequeue/postgresql.py
This way we can give them back cleanly if any errors happen while trying to use them.
=> Track connections before trying to use them

tests/test_metatile.py, tilequeue/metatile.py, tilequeue/store.py
When comparing zip files to see if the tile already in storage is the same as the one just generated, ignore the timestamp and archive file order, as these are likely to change between two renders. Instead, all we care about is that they contain the same set of files and that those files have identical content. 
Connects to #152.
@rmarianski, @iandees could you review, please?
=> Compare ZIP file ignoring metadata

tilequeue/wof.py
When we get invalid dates, we can have the edtf date api return back `None` for earliest/latest dates. This adds a check to guard against that, and return back a better error message in this case. Otherwise, the `min` or something else downstream will raise a general error when it's first used.
=> Return a better error for invalid dates

tilequeue/process.py
This is laying the groundwork for the zoom level and geographic coordinates to vary independently from one another. The unpadded coordinates are already stored in the post processing context, so we just need to pass in the nominal zoom (i.e: a measure of display scale) rather than the actual tile coordinate to ensure that post-processing steps are not dependent on the coordinate.
@rmarianski, @iandees could you review, please?
=> Don't pass tile coordinate to post-process functions.

config.yaml.sample, tilequeue/command.py, tilequeue/config.py, tilequeue/process.py, tilequeue/worker.py
This was used to generate extracts of specific layers to be stored in S3 so that they could be served directly for single layer requests. However, we now use a microservice called "xonacatl" to serve dynamic layers requests and so this functionality isn't needed any more.
=> Remove "layers to format" functionality.

tests/test_process.py, tilequeue/process.py
This changes the behaviour of the `cut_coords` parameter to `tilequeue.process.process_coord` so that any `cut_coords` ("children") are created by clipping the post-processed features of the main ("parent") tile rather than re-processing the children from the original, un-processed features.
This is likely to be faster, but probably only marginally as we currently only use `cut_coords` for tiles at zooms over 16, which generally have negligible post-processing time.
However, it does change the behaviour; re-processing the children tiles meant that post-processing filters would be run with the zoom of the child tile, whereas with this change it will just contain a subset of the data in the parent tile, which was post-processed at the zoom of the parent tile. This probably isn't an issue …
=> Make child tiles from parent rather than re-processing

tests/test_process.py, tilequeue/format/OSciMap4/TagRewrite/__init__.py, tilequeue/format/__init__.py, tilequeue/format/mvt.py, tilequeue/format/vtm.py, tilequeue/process.py, tilequeue/transform.py, tilequeue/worker.py
This removes a bunch of places where we were passing around a `coord`, but only needed a `zoom`. Removing the coordinate allows us to introduce an explicit `nominal_zoom` which controls the zoom level at which the post-processing runs, and may be different from the zoom level associated with the address of the tile and its bounds.
=> Use nominal zoom to control post-processing zoom

tilequeue/store.py
``tilequeue.store.TileDirectory`` must write files *atomicly* ..
problem description
-------------------------
* if server process will stopped suddenly -- cached must be protected from corruption. ``Gunicorn`` may kill process (any time) if timer of timeout of request elapsed
* cached must not able to read when it is not yet complete written.  ``Gunicorn`` runs several concurrent processes with one store directory.
patch details
----------------
introduced function ``os_replace(src, dst)`` for *unix-style* atomically file writing
=> ``tilequeue.store.TileDirectory`` must write files *atomically*

tilequeue/query.py, tilequeue/worker.py
This makes it easier to separate the zoom used for querying and postprocessing, which I've been calling `nominal_zoom` but would perhaps be better called "display zoom", from the zoom level used to indicate the spatial extent of the tile.
=> Query the DataFetcher at nominal zoom

tests/test_metatile.py, tilequeue/command.py, tilequeue/metatile.py, tilequeue/worker.py
This adds support for 2x2 metatile and lays the foundation for 512px tiles. It does this by making the tilequeue worker operate on metatile-sized work chunks, where that is identified by a lower zoom tile coordinate.
The database is queried for the spatial extent of the metatile, but with the "zoom level" parameters set to the `nominal_zoom`, which is a measure of display scale, rather than the zoom of the tile coordinate. The post-processing is also run at the `nominal_zoom`.
Following that, smaller tiles are cut from the metatile, and all of them are put into the zip file which is uploaded to S3. No extra processing is done, so all the feature selection is performed at the `nominal_zoom` in the database or post-processor. Tiles are formatted separately, so should not incur serialisation …
=> Add support for 2x2 metatile

tests/test_command.py, tests/test_wof_http.py, tilequeue/command.py, tilequeue/wof.py
Connects to https://github.com/mapzen/tile-tasks/issues/201
Refs https://github.com/mapzen/chef-mapzen_tilequeue/pull/29
This emits the stats to the log, and logstash will pick them up and send them over to statsd.
Longer term I think we should transition to the same approach we took in tapalcatl, namely to have the process itself send the stats directly.
=> Emit additional metrics during intersection

tilequeue/metatile.py
On a random tile that I was testing with, this reduced file size by 79%.
The compressed metatile will take up less space in storage and transfer more quickly over the network. The disadvantage would be the CPU time required to decompress it. Looking at CPU usage on the tapalcatl machines, it's fairly light at the moment, so we've room to do more there.
What do you think? Should I make it configurable in case we need to turn it off in a hurry?
=> Compress files in metatile.

tilequeue/worker.py
A couple of issues here:
1. Another `assert` was stopping the worker, this time when a coordinate was invalid. Perhaps we should put a general exception-catching block around the worker threads?
2. Some tiles which were in the TOI already and descended from the job coordinate were included in the tiles twice. This is only because the TOI contains 256px coordinates, rather than the 512px (i.e: `zoom - 1`, 2x2 metatile) coordinates, which shouldn't happen when we're fully switched over to 2x2 metatiles. But in the interim, seems like it would be better to be robust to these.
cc @rmarianski, @iandees. I'm merging this to unblock and continue, but would appreciate it if you could look it over and give me any advice you have for improving it, please.
=> Fix some more bugs in metatile work

tilequeue/transform.py
Drop parts of multipolygon inputs which lie outside the boundary of the tile, and clip to the clip boundary.
This can occur because we merge buildings with the same properties into large MultiPolygons. We want large buildings, such as the High Line, to continue beyond the bounds of the tile, but we don't need to keep other parts of the MultiPolygon which are completely outside of the tile. They'll be present in the neighbouring tile anyway.
This saves about 70% of the work of formatting the child tiles of a "512px" tile.
=> Drop MultiPolygon parts outside the tile

tilequeue/command.py, tilequeue/config.py
And change the default to depend on metatile size. The amount of data waiting in the queue can be quite large. The previous default of 128 combined with 2x2 metatiling would occasionally exhaust all the memory available on a host.
=> Make queue sizes configurable.

tilequeue/command.py, tilequeue/worker.py
Previously, jobs had just been ignored and allowed to time-out. This meant that they were added back to the queue after a timeout. Eventually, after some number of retries, they would be discarded. Deleting them means fewer retries.
This also moves rejection of jobs to SQS poll loop, which means that jobs get rejected more quickly, as they never get added to the worker's internal queue.
=> Delete rejected jobs from SQS queue.

tilequeue/transform.py
Was seeing this error in the logs. It appears to be because a MultiPolygon is being interpreted as a Polygon, and therefore has the wrong number of outer rings. To fix this, we just decompose the MultiPolygon into its constituent Polygons.
=> Fix LinearRing error

tilequeue/command.py, tilequeue/worker.py
MemoryError sometimes gets thrown when a very, very large message is put in a multiprocessing queue. This exception propagates up to the root of the thread and kills it, locking up the worker.
According to the Python docs, [MemoryError isn't entirely safe to recover from](https://docs.python.org/2/library/exceptions.html#exceptions.MemoryError), so instead this halts the whole process. It will be restarted by runit / systemd, and it might lose some work, but any lost jobs will be re-queued by SQS after a timeout.
=> Trap MemoryError, print a log message, and halt

logging.conf.sample, tilequeue/cache/redis_cache_index.py, tilequeue/command.py, tilequeue/tile.py, tilequeue/utils.py
Adding a command that prunes the tiles of interest by checking for tiles that were frequently requested and removing tiles from the tiles of interest set (and from S3) that **were not** frequently requested.
=> Command to automatically prune tiles of interest

tilequeue/command.py
Follows #176, adds the ability to list individual tiles that should stay in the TOI
=> Add the ability to list individual tiles that should stay in the TOI

tilequeue/command.py
Follow of #178, #176.
Standardize on 512px-sized tiles in the tiles of interest by "zooming out" the records from RedShift if they don't specify 512px as the requested tile size.
=> Account for tilesize on RedShift records

tilequeue/command.py
This adds the ability to include new tiles in the tiles of interest as part of the "prune" tilequeue command that was added in #176. This is a counterpart to https://github.com/tilezen/tileserver/pull/85, which pulls out the enqueueing and TOI adding piece from tileserver.
=> Add to tiles of interest as part of tilequeue "pruner" command

tilequeue/cache/redis_cache_index.py, tilequeue/command.py
A couple cleanups from #180.
- Have to include tilesize in the redshift group by query
- Filter out null tile coords that might sneak in to the immortal tiles section
- The redis client expects srem args to be a star-arg, not a list
=> A couple cleanups from running the gardener locally

tilequeue/command.py, tilequeue/worker.py
This allows us to specify a maximum number of tiles to include from RedShift in the tiles of interest (the "immortal tiles" will always be included). It also adds a tile request count cutoff. These two cutoff values should let us more carefully specify how much work we want tilequeue to do.
=> Add configurable request and tile count cutoffs

config.yaml.sample, tests/test_config.py, tilequeue/command.py, tilequeue/config.py, tilequeue/worker.py
This gets run when enqueueing the tiles of interest, when we deploy to prod and enqueue all the tiles. This should be set to z15 now.
This wasn't changing really changing before, but maybe this should be set from configuration now? Or perhaps we do it next time if/when this changes?
=> Move the zoom to enqueue to 15

tilequeue/command.py
current_date returns only the date, not the whole datetime. getdate() returns the current datetime.
=> Use getdate() instead of current_date in RedShift query

tilequeue/command.py
Got this while trying to seed the TOI:
```
Traceback (most recent call last):
File "/usr/local/bin/tilequeue", line 11, in <module>
load_entry_point('tilequeue==1.6.0', 'console_scripts', 'tilequeue')()
File "/usr/local/lib/python2.7/dist-packages/tilequeue/command.py", line 1589, in tilequeue_main
args.func(cfg, peripherals)
File "/usr/local/lib/python2.7/dist-packages/tilequeue/command.py", line 947, in tilequeue_enqueue_tiles_of_interest
if coord.zoom <= cfg.enqueue_max_zoom:
AttributeError: 'Configuration' object has no attribute 'enqueue_max_zoom'
```
Should that be just `max_zoom` now?
=> Replace 'enqueue_max_zoom' with 'max_zoom'

config.yaml.sample, tilequeue/command.py
Removing the namespace makes the configuration similar to the others, which means we don't need to make any changes on the chef side to generate the config.
=> Remove the s3 config namespace

tilequeue/command.py
The s3 namespace was removed from the config, and the guard needs to get
updated to trigger the logic to add in the integration test tiles into
the immortal set.
=> Update info guard

tilequeue/process.py
Connects to https://github.com/mapzen/tile-tasks/issues/239
This splits up the processing and formatting of tile data into separate steps that can be called individually. This allows tileserver to perform a step in between, namely to filter out layers that were not a part of the original request. Then, it can format the subset of resulting layers.
Also, the preprocess and process functions have been merged into one. I think the reason they were separate had to do with a where some feature filtering occurred, which is no longer relevant. This means that we don't have to iterate through all features twice (once for pre-process and then again for processing).
Additionally, all references to using the zoom from the tile coordinate have been moved to using a passed in nominal zoom.
=> Factor process_coord into processing/formatting

config.yaml.sample, tilequeue/command.py, tilequeue/config.py, tilequeue/worker.py
The store_metatile_and_originals config is no longer used. It was removed from tileserver as part of https://github.com/tilezen/tileserver/pull/94
=> Remove store_metatile_and_originals config

tilequeue/command.py
`Tilequeue seed` fails if **should-add-to-tiles-of-interest** is set and TOI-set file doesn't exist.
Instead of creating toi.txt and then calling `tilequeue load-tiles-of-interest`, `tilequeue seed` should be able to proceed with empty TOI if none was created.
=> create a TOI set on seed if toi-set file doesn’t exist

tilequeue/command.py
Resolved the exception in default_queue_buffer_size when `metatiles_size` is set to **null**
=> default_queue_buffer_size fix when metatiles are disabled

tilequeue/command.py
store: path: not used for directory store fix
=> store: path: used for directory store

config.yaml.sample, tilequeue/command.py
Allow specifying a single file that contains expired-tiles in addition to directory
=> intersect supports single file

logging.conf.sample, tilequeue/command.py
After we migrate the tiles of interest set from Redis in #193, we should merge this PR so that the command that dumps from Redis is removed.
=> Remove Redis TOI dump command

tilequeue/command.py
Like tilezen/mapbox-vector-tile#91, but for tilequeue.
=> Enable Shapely speedups when they're available

tilequeue/command.py, tilequeue/config.py, tilequeue/store.py
The `delete_keys` method used to delete tiles from S3 returns an object containing both successes and failures, and does not raise an exception for failures. This means that rare or intermittent errors can result in some tiles not being deleted. Adding a retry mechanism should make sure that is not the case. Although the loop is infinite, the assumption is that errors from S3 are rare and that dealing with them this way is easier than adapting the API of the object to handle returning failure coordinates back to the main process.
=> Retry deleting tiles on S3.

tilequeue/command.py, tilequeue/postgresql.py, tilequeue/process.py, tilequeue/query.py, tilequeue/worker.py
Connects to https://github.com/mapzen/tile-tasks/issues/267
Links up with https://github.com/tilezen/tileserver/pull/110 and https://github.com/tilezen/vector-datasource/issues/1352.
=> Makes queries per-table

tilequeue/command.py, tilequeue/query/__init__.py, tilequeue/query/postgres.py
This is a small tidy-up to move a bunch of Jinja2 specific code into a module. The idea is that we can start separating the parts of the code which are specific to PostgreSQL from the general parts using the `DataFetcher` interface. Then we can implement additional things conforming to `DataFetcher`, such as RAWR tiles.
=> Tidy things up for a data fetcher interface.

tests/test_query_fixture.py, tilequeue/query/__init__.py, tilequeue/query/fixture.py
This adds a fixture-based data source, which returns data in a similar format to the data coming from PostgreSQL, so that it can be processed in the same way by the rest of the system. The idea is to use it for tests before widening the implementation to include RAWR tiles.
Starts to lay the foundation for tilezen/vector-datasource#923.
=> Fixture-based data source

config.yaml.sample, logging.conf.sample, tilequeue/command.py
This command can be given a list of tiles and it will print out its in-flight, TOI and storage status. This can be helpful while debugging "stuck" tiles, although in the time it took me to write the tool, the issue [was probably self-fixed by the gardener](https://github.com/tilezen/vector-datasource/issues/1363#issuecomment-320227790).
I had to do some work-around-y stuff to pass the positional `coords` arguments to the `command_tile_status` function, so I'd very much appreciate any recommendations about how that might be done more neatly or cleanly.
=> Add a tile status command

tilequeue/command.py
Previously, the command fn bound for a parser would always be the last
one. This creates a new function instead of each binding to the same
one.
=> Correct function used for parser

logging.conf.sample, tilequeue/command.py, tilequeue/store.py
Related to root cause analysis of https://github.com/tilezen/vector-datasource/issues/1363 and https://github.com/tilezen/vector-datasource/issues/1320. This new script will be used to list and then delete stuck tiles.
Followup will be filed relating to TOI Gardener config for root cause fix.
=> Add tilequeue command to list stuck tiles

tests/test_query_fixture.py, tilequeue/process.py, tilequeue/query/__init__.py, tilequeue/query/fixture.py, tilequeue/tile.py
This is mostly changes to the "fixture DataFetcher" to make the same transforms as are being done by the PostgreSQL queries. This is enough to support running all but one integration test from the vector-datasource repo. (The one which still fails is due to station relation walking not yet being implemented well enough to handle the `root_relation_id` stuff.)
There are a few TODOs left here, but it's already getting to be a big patch, so I'd like to see what you think before going any further.
=> Support for local fixtures

tests/test_query_fixture.py, tilequeue/query/fixture.py
This is used to recurse up through transit relations to find the "root" transit relation ID, which can be used to group together all the features which are part of the "same" station.
Related: https://github.com/tilezen/vector-datasource/issues/1392
=> Add option to pass all relations to fixture data fetcher.

requirements.txt, setup.py, tilequeue/query/rawr.py
Previously was using a hand-rolled `enum` for simplicity, but the code was becoming less simple. Using the enum package simplifies it a bit.
=> Use enum34 package to provide enumerations.

tilequeue/command.py, tilequeue/rawr.py, tilequeue/wof.py
=> Update wof process to enqueue to rawr queue

logging.conf.sample, tilequeue/command.py
In preparation for updating logging, I noticed that some commands that were either very old or never been run, ie dead code. Some of these were using loggers, so now seems like as good a time as any to remove them.
=> Remove unused commands

tests/test_metatile.py, tests/test_query_rawr.py, tests/test_query_split.py, tests/test_utils.py, tilequeue/command.py, tilequeue/metatile.py, tilequeue/query/__init__.py, tilequeue/query/common.py, tilequeue/query/fixture.py, tilequeue/query/postgres.py, tilequeue/query/rawr.py, tilequeue/query/split.py, tilequeue/rawr.py, tilequeue/utils.py, tilequeue/worker.py
Added the ability to load RAWR tiles for processing from S3, or generate them directly from the database. The latter is useful for testing, and bypasses the round-trip via the msgpack-encoded `.zip` file, but is otherwise identical (and takes a while).
Added a `DataFetcher` implementation which is able to dynamically switch between database and RAWR tiles based on the zoom level(s) of the incoming tiles.
Plenty of TODOs in here to follow up, but hopefully this is a "save point" and we can clear the TODOs up afterwards.
=> Hook up RAWR data fetcher

logging.conf.sample, tilequeue/command.py, tilequeue/log.py, tilequeue/worker.py
A new logging abstraction was created, and the processing worker classes now all use it for logging.
I expect this to conflict with https://github.com/tilezen/tilequeue/pull/255. I'm happy to resolve any conflicts once that gets merged, since the changes I've made are all just logging based and will not have changed any of the logic.
=> Add json logging to tilequeue processing

tests/test_query_fixture.py, tilequeue/query/fixture.py
Current [integration test failures](https://circleci.com/gh/tilezen/vector-datasource/2040) over in [`vector-datasource`](https://github.com/tilezen/vector-datasource/) are because I dropped the `source` tag in commit 1326573 because in practice we override it with our own definition of the source of the data. 
However, I forgot to add the tag back in for the fixtures, meaning that a whole chunk of logic which depends on the source was failing.
This adds the tag back in for fixtures, and adds a unit test to make sure that it stays there.
=> Fix fixture source property

logging.conf.sample, tilequeue/command.py, tilequeue/rawr.py
This command will effectively replace the other seed command for our purposes. Higher zoom level tiles will get enqueued onto the rawr queue that need to get grouped, and after the rawr tile gets generated, the children tiles of that rawr tile will get enqeueud for processing. Low zoom level tiles will get enqueued directly to the tilequeue processing queues.
If we wanted to split this apart a little bit more in the future, we'd need to have the consumers know that these tiles enqueued for processing are for rawr tile generation only, and not for subsequent tilequeue processing, as is the typical workflow after applying diffs.
=> Add rawr-seed-toi command

config.yaml.sample, tilequeue/command.py
Without the region, creating the client fails on ec2 instances. Locally this works for me because I have a default region set up in my .aws/config.
I could have most likely also fixed this by setting an environment variable on the command, but I think having it in the tilequeue config file is nice because it's all in the same place that way.
=> Add region to boto3 sqs/s3 clients

tests/test_query_fixture.py, tests/test_query_rawr.py, tilequeue/process.py, tilequeue/query/__init__.py, tilequeue/query/common.py, tilequeue/query/fixture.py, tilequeue/query/rawr.py, tilequeue/rawr.py
* Add support for stations being multipolygon relations (already had support for nodes and ways).
* When assigning names to one of `pois`, `landuse`, `buildings`, assign all name variants and translations, not just `name` itself.
* Remove the hard-coded OSM "source" from RAWR, and make it something that is provided by the table and configurable.
Note that I initially tried to make "source" an `Enum`, but this turned out to create more difficulties than it solved, as it made it much harder to inject custom, unique sources for testing purposes. It would also make it very difficult to extend `vector-datasource` or 3rd party styles to additional data sources. Instead, I've replaced it with a `Source` `namedtuple` which contains both the short name (e.g: `osm`) and the long name that we use as …
=> Fix some RAWR-related TODOs

tilequeue/log.py
=> Log coordinates as integers

config.yaml.sample, tilequeue/command.py, tilequeue/config.py, tilequeue/query/__init__.py, tilequeue/rawr.py, tilequeue/store.py
Both for reading and writing. This patch means that it's possible to configure a store to round-trip RAWR tiles locally. For example, with the following RAWR config:
```yaml
rawr:
group-zoom: 10
queue:
type: mem
name: myrawrqueue
input-file: rawr_input.txt # this just contains 10/163/395
postgresql:
host: null
port: 5432
dbname: california
user: matt
password: null
store:
type: directory
path: rawr_tiles
source:
type: store
store:
type: directory
name: rawr_tiles
postgresql:
host: null
port: null
dbname: california
user: matt
table-sources:
planet_osm_line: &osm { name: osm, value: openstreetmap.org }
planet_osm_point: *osm
planet_osm_polygon: *osm
planet_osm_ways: *osm
planet_osm_rels: *osm
use-rawr-tiles: true
```
I'm able to run:
```
tilequeue rawr-process --config config.yaml …
```
=> Add support for local storage of RAWR tiles.

tilequeue/log.py, tilequeue/rawr.py, tilequeue/stats.py
Refs https://github.com/tilezen/raw_tiles/pull/9
=> Emit more detailed timing and stats

config.yaml.sample
As raised in #277, we didn't describe how to configure 512px tiles. This patch updates the comment, making it clearer how to enable 512px tiles and what additional effects that will have (i.e: `.zip` metatiles, requiring tapalcatl).
=> Add configuration comment about metatile size 2

tests/test_query_common.py, tests/test_query_rawr.py, tilequeue/query/__init__.py, tilequeue/query/common.py, tilequeue/query/rawr.py, tilequeue/rawr.py, tilequeue/tile.py
A slightly random grab-bag of changes that were necessary to get RAWR tiles rendering in a not-awful way.
* Cache the bounds of a `LazyShape`, and use that to skip unnecessary calls to geometry intersection. This doesn't save as much time as I'd have hoped, but it seems like a relatively benign bit of code to leave in.
* Store sorted list of route names, rather than set. Some versions of `ujson` seem to be unhappy with serialising a set. I think the version we're using in prod is okay, but I managed to randomly update mine locally while playing around with different Shapely versions.
* Handle missing nodes, ways and relations in the index. In an attempt at efficiency, I try to only index elements which are "interesting" and have a high likelihood of being looked up. However, at …
=> Various RAWR tile fixes

tests/queue/test_msg.py, tests/queue/test_sqs.py, tilequeue/command.py, tilequeue/log.py, tilequeue/queue/message.py, tilequeue/queue/sqs.py, tilequeue/rawr.py, tilequeue/worker.py
Simplify the msg tracking logic. This should hopefully remove the errors we've been seeing. If not, instead of failing with an error, it tries to always proceed now but emit a warning in the logs for any inconsistencies.
The simplification changes:
* don't use memory ids as the indirect coord/queue handles
* use the queue message receipt handle as the key for mapping to the set of coord ids
* use a coordinate z,x,y tuple as the coord id
* use the coord_id and queue_handle_id as the coord handle, which removes the need for another intermediary mapping
The sqs queue implementation was also updated to use boto3. This was necessary to gain access to the receipt handle directly. Actually, it might have been possible with boto2 as …
=> Simplify coord -> queue msg handle mappings

tilequeue/command.py
Only the first (zero'th) JSON tile will be output, so this isn't terribly useful in the command itself, but can be very useful when trying to replicate failures on a single (meta)tile.
=> Add support for configured nominal zoom to single tile processing.

tilequeue/command.py, tilequeue/stats.py, tilequeue/worker.py
I was looking through grafana and stats, and made a couple of updates:
* added fetch/proc stats that we can use to get a count on the dashboard
* namespaced timing stats more consistently
NOTE: I optimistically based this pr off of https://github.com/tilezen/tilequeue/pull/298 since some of the code was in a similar location.
=> Update tilequeue proc stats

config.yaml.sample, tests/test_query_rawr.py, tilequeue/command.py, tilequeue/query/__init__.py, tilequeue/query/rawr.py, tilequeue/rawr.py
Added support for extra data tables, including indexing them. Made indexing configurable so that it is (in theory, at least) not hard-coded to our schema. Updated to match changes in https://github.com/tilezen/raw_tiles/pull/17.
=> Add extra data tables

config.yaml.sample, tilequeue/command.py, tilequeue/rawr.py
=> Add additional rawr intersector implementations

tilequeue/command.py
The toi-store s3 config is namespaced under the type, s3. This updates
the rawr toi-store config parsing to get the bucket from the right
location.
=> Update rawr intersect config parsing

tests/test_mvt.py, tilequeue/config.py, tilequeue/format/__init__.py, tilequeue/format/mvt.py, tilequeue/format/topojson.py, tilequeue/process.py, tilequeue/tile.py
This makes it so that all the tiles in a metatile have the same precision. That means that if the "256px" tiles have extent 4096, the "512px" ones are 8192 and so forth. Also adds a test to check that "1024px" tiles come out correctly when configured.
There will be a follow-on PR to make some of these optional, in case we don't want the "1024px" tile (although it will still have to be generated, just missing from the formatted coordinates).
=> Same precision for metatiles

config.yaml.sample
Thanks to @rmarianski for spotting this omission!
=> Add config for urban areas data source.

tests/queue/test_msg.py, tilequeue/command.py, tilequeue/config.py, tilequeue/queue/message.py, tilequeue/worker.py
Various random issues that came up while running the RAWR tiles TOI through dev at 4x4 metatile size:
1. Because our TOI metatile size was 2x2 and therefore mismatched with the 4x4 metatile size of jobs we were rendering, some jobs rejected all the tiles in them (because they were at z15, which doesn't exist for 4x4 - it stops at z14). This was causing exceptions to be thrown when trying to access properties of `top_tile`, which was `None`. This change discards those jobs before they are sent for rendering, which is safe because the message tracker will have already ACKed them when the final coordinate was rejected.
2. Possibly also related to metatile size mismatch; we were getting duplicate coordinates in the job. This broke the message tracker, which uses coordinates as unique keys. …
=> Miscellaneous RAWR tile fixes

tests/test_tile.py, tilequeue/command.py, tilequeue/tile.py
This changes the TOI gardener/pruner to parse the tile size and use the configured metatile size to up-zoom access logs to the metatile they're part of.
=> Configurable up-zooming of tiles from Redshift

tilequeue/command.py
At some point we updated the store creation code to take a config dictionary rather than individual arguments, but missed some calls to it. This refactors most of those calls into a single local function, which should make it easier to change in the future.
=> Refactor store creation in command.py

tests/queue/test_mapper.py, tilequeue/command.py, tilequeue/queue/mapper.py
This adds the ability to filter to a different queue depending on whether the coordinate is part of the TOI or not. This means that we can configure different setups, such as:
1. Queue filter by zoom, intersect on TOI: Current configuration, renders the TOI only.
2. Queue filter by TOI, intersect all tiles: "Global build" configuration, renders all tiles, but can send TOI tiles to a higher priority queue.
The configuration should allow flexible priorities, for example whether all TOI comes before all non-TOI, or whether they're interleaved by zoom.
=> Filter to different queue based on TOI membership.

tilequeue/command.py, tilequeue/log.py, tilequeue/rawr.py, tilequeue/stats.py
=> Move intersection to rawr enqueue step

tilequeue/command.py, tilequeue/rawr.py
Also adds more information about the cause of the failure, as returned in the SQS failed messages.
=> Add backoff and retry to RAWR tile enqueuing.

tests/test_query_common.py, tilequeue/query/common.py
Sometimes there are additional `modifier` tags on route relations which alter the interpretation of the route, for example; local business or spur sections of the route. [We would prefer that these are part of the network property](https://github.com/tilezen/vector-datasource/issues/1387), which they often already are.
This modifies the tags during the query process and tests the expected transform. There will be a follow-up PR to `vector-datasource` to add integration tests and an equivalent transform to the SQL.
Connects to https://github.com/tilezen/vector-datasource/issues/1387.
=> Add route modifiers to network property.

tilequeue/command.py
Batch process was calling `process_coord` with the `coord.zoom` rather than the nominal zoom, meaning that all tiles were 4096 in size, and also had lower levels of detail than intended.
=> Use nominal zoom in batch process.

tilequeue/command.py, tilequeue/log.py
Additionally, tiles that error out will be skipped and the run will
proceed rather than terminating on the first error.
=> Add logging to batch processing

tilequeue/queue/message.py
The single and multiple message per coord tracker queues are used
interchangeable on a config value, but the methods have not
the same count of arguments. This commit fixes the resulting crash
by adding the missing, unused parameter to the track function
of the SingleMessagePerCoordTracker class
=> fix crash on using the single queue type

tilequeue/process.py
The source for the `buffered_land` changed to `tilezen.org`, which requires that tilequeue understands what that means (this is probably a design flaw / unnecessary coupling that we should fix). This PR adds that.
Connects to https://github.com/tilezen/vector-datasource/issues/1482 and https://github.com/tilezen/raw_tiles/pull/20.
=> Add new source for tilezen.org.

tests/test_store.py, tilequeue/command.py, tilequeue/store.py
This changes the tile store implementation to use `boto3` rather than `boto` version 2. It also has a few random fixes, and extra configuration parameters.
* There's more verbose error logging for S3 errors. It now prints out the bucket and key, which should make tracking permissions errors down a bit easier.
* Use the region from the environment for Batch, if it's available. This means we're not hard-coded to `us-east-1` any more.
* Configurable object ACL. We use, `public-read` in Nextzen and this will be the default, but others may want `private`.
=> Use boto3 for tile store

tilequeue/store.py
D'oh! `StringIO` doesn't have a `.bytes()` function! I was probably thinking in Go when I wrote that. The effect was that Batch jobs would fail immediately when they attempted to fetch a tile which had already been rendered.
=> Fix incorrect method call on StringIO in store.

tilequeue/process.py
We've hardcoded a bunch of layer names in here, which isn't great. We should come back at a later date to make that more configurable. Until then, this just extends the list to include the new entry.
Related to: https://github.com/tilezen/vector-datasource/pull/1499
=> Add admin areas.

config.yaml.sample, tests/test_config.py, tests/test_process.py, tilequeue/command.py, tilequeue/config.py, tilequeue/process.py
The previous behaviour to generate all the tiles of different sizes within a metatile. That worked great while we were generating 512px and 256px tiles in a size 2 metatile. It kinda worked while we were generating 1024px, 512px and 256px tiles in a size 4 metatile. However, moving to a size 8 metatile means we're duplicating information across 4 different sizes of tile - two of which we don't use ever, and the last one we rarely use.
This change introduces configurable tile sizes within a metatile. For example, it's possible to specify just 256, just 512 or both. This will cut down on extra, unwanted data in metatiles.
There are some special cases to this:
For maximum nominal zoom tiles, smaller tiles are always included even if not configured. This means that if the maximum nominal zoom …
=> Configurable tile sizes with a metatile

config.yaml.sample, tests/test_command.py, tilequeue/command.py, tilequeue/log.py
This effectively unpacks the batch job types at the queue zooms (z7) one level to take advantage of batch array jobs. This involves updating the enqueue process to be set the correct job size, and modifying the rawr/low/high tile generations to be aware of this.
Unfortunately, the diff looks more aggressive than it is because the indentation changed throughout, but it boils down to removing the outer loop around what the z7 tile represents.
=> Model batch jobs as aws batch array jobs

config.yaml.sample, tests/test_command.py, tilequeue/command.py, tilequeue/log.py
In #347, we started to use [AWS Batch array jobs](https://docs.aws.amazon.com/batch/latest/userguide/array_jobs.html) so that we didn't have to manually "unpack" a job as a zoom 7 coordinate into its zoom 10 descendants. This should have had the advantage of each individual zoom 10 job being scheduled independently, leading to better load balance.
Unfortunately, we ran into some problems with the array jobs which drastically reduced throughput. Until those are cleared up, for practical reasons it's necessary to revert back to the old way of doing things.
=> Revert back to using individual jobs.

README.md, tilequeue/format/__init__.py
It's like the existing MVT driver, but using [coanacatl](https://github.com/tilezen/coanacatl) instead of [mapbox_vector_tile](https://github.com/tilezen/mapbox_vector_tile).
It needs extra stuff installed, so it's optional at the moment. I've added a subsection to the README to call that out.
=> Add new coanacatl driver

tilequeue/command.py
I think this got lost in a refactor at some point, but the loop should continue to the next tile after logging the exception.
=> Add missing 'continue' statement after logging exception.

tests/test_store.py, tilequeue/store.py
By configuring the store bucket name as a list, this adds the ability to write to that list of buckets in order.
Connects to #353.
=> Write to multiple buckets.

tests/test_process.py, tilequeue/process.py
The code was passing the coordinate max zoom to `calculate_sizes_by_zoom`. For example, with 8x8 metatiles and a max nominal zoom of 16, it would pass 13. This meant that 256px tiles were being generated for 3 more zoom levels than we really needed.
Added comments saying it's coordinate zoom and fixed the tests to pass in the coordinate zoom, with a one-line update to the method itself. This should mean we only get 256px tiles at max zoom, and not before.
=> Fix high zoom 512/256 tile size

tilequeue/command.py
The `simplify_and_clip` post-processing transform looks in the layer datum to get the tolerance factor to use for simplifying geometries. Turns out, this wasn't getting passed through from the `queries.yaml` config, so it was just using the default of `1.0` for every layer. Ooops.
=> Pass the tolerance from config through to layer datum.

tests/test_query_rawr.py, tilequeue/query/rawr.py
We don't query boundaries at all from the `planet_osm_lines` table, instead we select the polygons and generate linestring boundaries from them. This is to ensure that boundaries are correctly oriented with the interior on the left.
However, we weren't doing this for RAWR tiles, and were using the lines from `planet_osm_lines` in their original orientation. The `planet_osm_lines` table contains multiple copies of the line; from the original way, plus any boundary relations it is part of. This meant that the two linestrings making up a section of border were in the same direction, and therefore the boundary would be flipped if the geometry was "used" by the wrong side first (which depends on the order in the file, which is non-deterministic).
The fix for this is a bit of an egregious hack; …
=> Process boundaries from RAWR tiles the same way we do from SQL.

tilequeue/format/vtm.py
Seems like it doesn't like the 8-space indent that some of the lines in the VTM format code use.
=> Fix indentation for new, stricter flake8.

tests/test_query_rawr.py, tilequeue/query/rawr.py
We include buffered land into the boundaries table, but we want to keep it as a polygon, not turn it into a set of outer/inner ring linestrings.
Note: Tests will fail, will need to rebase onto #366 for fix.
Connects to https://github.com/tilezen/vector-datasource/issues/1811.
=> Exclude buffered land polygons from changes made in #362.

tests/test_query_rawr.py, tilequeue/query/rawr.py
In the boundary code, we ensure that admin polygons are correctly oriented, with the interior on the left of their rings, before extracting those rings as boundary lines. However, the orient function from Shapely only handles Polygons, not MultiPolygons, and bails with an exception if it encounters a MultiPolygon. Sadly, many admin areas are indeed MultiPolygons. This adds a simple utility function to orient MultiPolygons by orienting all constituent Polygons.
=> Add utility function to orient MultiPolygons.

tilequeue/command.py, tilequeue/tile.py
Allow coordinates for high zoom meta jobs to be anywhere between the `queue_zoom` and `group_by_zoom` (i.e: RAWR tile zoom) inclusive. That's usually between 7 and 10, respectively. This means we can submit jobs which take a long time individually at zoom 10, rather than grouping them at zoom 7 to reduce the overall number of jobs.
Connects to https://github.com/tilezen/tileops/issues/17, required by https://github.com/tilezen/tileops/pull/47.
=> Reduce high zoom "long tail" of jobs

config.yaml.sample, tilequeue/process.py, tilequeue/query/rawr.py
Connects to https://github.com/tilezen/vector-datasource/issues/1855.
=> OpenStreetMapData.com is now hosted by FOSSGIS at osmdata.openstreetmap.de

tilequeue/query/rawr.py
Wikidata was added to RAWR tiles in https://github.com/tilezen/raw_tiles/pull/31, but needs to be joined to the OSM features to make it useful. This adds the properties associated with the wikidata to the OSM feature when the OSM feature has a `wikidata` ID matching a row in the wikidata RAWR "table".
This is used to set `passenger_count` on `kind: aerodrome`, which is then used to set `kind_detail: international` on very large airports.
Connects to tilezen/vector-datasource#1873. Depends on https://github.com/tilezen/raw_tiles/pull/31.
=> Inject wikidata from RAWR tile into OSM features.

tilequeue/query/rawr.py
In tilezen/vector-datasource#1895, I added a little hack to work around the way we change the geometry type of `boundaries` layer features. They used to come entirely from the `planet_osm_polygon` table, but now we also include disputes and claims from `planet_osm_line`. However, we have to filter out a bunch of features from `planet_osm_line` that we don't want, but have the same tags as the polygons we do want.
Long story short: The query in `vector-datasource` sets this flag when transforming a polygon into a boundary line, so we have to do the same thing when reading from the RAWR tiles.
Connects to tilezen/vector-datasource#1810.
=> Alternate viewpoints changes for RAWR tiles.

tilequeue/process.py
Connects to tilezen/vector-datasource#1859.
=> Remove transitionary alias used for osmdata sources.

tests/test_query_rawr.py, tilequeue/query/rawr.py
Fixes build problems discovered during the v1.8d build:
1. The code was dropping all linestrings. This used to be the correct behaviour, but now claims and disputes are included as line features and these should not be dropped any more.
2. After converting from the polygon to the boundary, the `mz_boundary_from_polygon` flag was being set on the wrong set of properties. This caused a downstream process to explode, since the feature no longer matched any of the YAML rules.
=> Fix problems with disputed boundaries from RAWR tiles

tilequeue/command.py, tilequeue/config.py
In order to better debug what's inside the config, add a string repr for the Configuration object.
Also in order to provide a way to override certain config values from triggering time, add a few arguments to some tile commands so that those config values can be provided by the trigger.
Temporarily modify the tilequeue_main to print out the `cfg` variable after make_config_from_argparse call. Then in local virtual env do `pip install -e .`
Then trigger the command by 
```
tilequeue meta-tile-low-zoom --config /Users/pli/config/meta-low-zoom-batch-config.yaml --tile '7/20/44' --run_id=20210426-peiti --postgresql_host '["host.docker.internal"]' --postgresql_dbnames '["gis"]' --postgresql_user gisuser --postgresql_password VHcDuAS0SYx2tlgT --store_name '["my-meta-tiles-us-east-1"]' …
```
=> Add string representation for config and config override

README.md, tilequeue/command.py, tilequeue/query/__init__.py, tilequeue/store.py
Add support to assume IAM role for accessing S3
At the same time remove a credentials read path since that is not used at all.
Tested manually that it works.
=> Add support to assume IAM role for accessing S3

tilequeue/command.py, tilequeue/config.py, tilequeue/query/__init__.py
We added support to assume the IAM roles in #391, however for high zoom meta tiles, some extra configs still need to be made, thus this PR.
Also removed the two arguments  query_cfg, io_pool from make_data_fetcher method since they are not used at all.
=> Add config override support for high zoom build

tilequeue/log.py
to make rawr tile message in parity with high/low zoom meta tile, we add a message to rawr tile logger.
=> Add message to rawr tile processed

tilequeue/command.py, tilequeue/log.py
In order for some consumer to know how much time it takes for a coord render, we need to log this information.
=> Add coord process total time to log

tests/test_store.py, tilequeue/command.py, tilequeue/query/__init__.py, tilequeue/store.py, tilequeue/utils.py
Some tiles that takes a long time won't finish in one session, so we need a client which can refresh credentials automatically.
=> Add AWS credentials refresh client helper

tilequeue/command.py, tilequeue/config.py
meta-tile command (highzoom) expects to have two configurations for the s3 buckets, one for its output and one that it depends on: the rawr tile bucket. 
We need to provide separate overrides for these two buckets.
=> separate metatile rawrtile buckets config override

tests/test_wof.py, tilequeue/wof.py
Right now, we join these hstore expressions with a "," but we don't escape strings that contain commas.   It turns out that in previous cases when we had items with commas in them, they also had spaces like 'Lincoln, Nebraska', so our hstore escaper would surround it with quotes because of the space, but we also want to do it even if there is no space.
=> add comma as character to put in quotes

tests/test_mvt.py, tilequeue/process.py
The scale used to be 8192 in some circumstances, but we think that's not necessary so we reduce it to 4096 for all zooms.
Rebuilt England area using with the change and found all zooms extent are 4096 now.
=> make every zoom's tile use 4096 as extent

tilequeue/command.py, tilequeue/process.py, tilequeue/query/__init__.py
just what the title says. you can now modify queries.yaml to reference layers from mercator projected geojson files. the way in which ive implemented this is fairly lightweight in that we dont support transforms or filters on the initial data (ie we dont load any yaml files like water.yaml buildings.yaml etc) because we expect the layer to be pretty much already in its final format. this does mean however that postprocessing transforms are allowed since they dont have any filtering or column juggling.
this pr is a corollary to the one over here: https://github.com/tilezen/vector-datasource/pull/2095
=> add support for preprocessed inline geojson layers

tilequeue/store.py
Adding a new keyFormat type `simple` that doesn't include the hash.
=> adding a keyFormatType without a hash

requirements.txt
```
boto3==1.15.18
botocore==1.18.18
```
is necessary for the s3 role assume to work.
Manually tested on tile build machine for these versions
=> Update requirements.txt to pin boto3 and botocore

.pre-commit-config.yaml
flake8 host has been moved from gitlab to github, so change it.
=> Update flake8 precommit hook
