tilequeue/command.py, tilequeue/transform.py
Issue https://github.com/mapzen/vector-datasource/issues/130
=> Support configuration for simplification starts

tilequeue/process.py, tilequeue/transform.py
=> Simplify geometries during processing step

tilequeue/process.py
Refs mapzen/vector-datasource#151
=> Filter out geometries with a small area

tilequeue/store.py
Refs https://github.com/mapzen/tileserver/issues/1
=> Add read_tile to store interface

tilequeue/wof.py
Connects to https://github.com/mapzen/vector-datasource/issues/147
=> Only update the wof data when changes exist

config.yaml.sample, tilequeue/cache/__init__.py, tilequeue/cache/stub_index.py, tilequeue/command.py, tilequeue/config.py
=> Add stub implementation for redis cache index

tilequeue/process.py
Connects to mapzen/TileStache#79.
=> Re-check polygon validity after call to buffer, just in case.

config.yaml.sample, tests/test_wof.py, tilequeue/command.py, tilequeue/wof.py
Depends on https://github.com/mapzen/vector-datasource/pull/365
* Add wof-load-initial-neighbourhoods command
This will be run initially to load up the database the first time. It
requires a local checkout of the WOF data repository on the filesystem.
* Update wof-process-neighbourhoods command
Instead of truncating everything and re-inserting, start tracking the
additions, modifications, and removals and execute the necessary sql to
sync neighbourhoods.
=> Update WOF processing pipelines

config.yaml.sample, tests/test_wof.py, tilequeue/command.py, tilequeue/wof.py
Refs https://github.com/mapzen/vector-datasource/issues/337
Connects with https://github.com/mapzen/vector-datasource/pull/378
=> Include microhoods and macrohoods

tilequeue/wof.py
=> Reproject geometry to mercator

tilequeue/wof.py
Connects with: https://github.com/mapzen/vector-datasource/pull/379
=> Track mercator area in separate column

tilequeue/wof.py
Refs:
* https://github.com/mapzen/vector-datasource/issues/338
* https://github.com/mapzen/vector-datasource/issues/386
Connects with: https://github.com/mapzen/vector-datasource/pull/392
=> Add min_zoom, max_zoom, is_landuse_aoi attributes

tilequeue/wof.py
Connects with: https://github.com/mapzen/vector-datasource/issues/393
This isn't finished yet, but the basic structure of how to handle failures should be in place.
@zerebubuth: could you take a quick look and let me know if I went down the wrong path, or if you have any suggestions thus far?
=> Add resilience to WOF imports

tilequeue/wof.py
This handles the edge case where the `superseded_by` is set in the json file but not in the meta csv.
=> Add handling for superseded_by inconsistencies

tilequeue/wof.py
@zerebubuth, @nvkelso: could you review please?
=> Escape string values in sql

tilequeue/wof.py
=> Update failure logging to stay on one line

tilequeue/wof.py
Refs https://github.com/mapzen/vector-datasource/issues/403
=> Remove neighbourhoods that became funky

tilequeue/tile.py, tilequeue/wof.py
@zerebubuth: could your review please?
=> Move reproject_lnglat_to_mercator function

config.yaml.sample, tilequeue/command.py, tilequeue/config.py, tilequeue/store.py
Refs https://github.com/mapzen/tilequeue/issues/31
Connects with https://github.com/mapzen/tileserver/pull/10
Prefix the s3 path with a date and the first 5 characters of the url md5 hash
=> Update s3 path

tilequeue/command.py
Updates the signature to be more flexible to support usage from
tileserver.
=> Update make_queue signature

tilequeue/process.py
Pass unpadded bounds to any post-process function with 'bounds' as a kwarg.
This seemed preferable to passing it to all functions and having to change the function signature of all the functions. Although if we find ourselves doing this again, might be better to pass a context object which we can extend.
Connects to mapzen/vector-datasource#502.
=> Pass bounds to post-process functions.

tilequeue/command.py, tilequeue/wof.py, tilequeue/worker.py
=> Metatile at z16

tests/test_config.py, tests/test_store.py, tilequeue/command.py, tilequeue/config.py, tilequeue/process.py, tilequeue/store.py, tilequeue/worker.py
Connect to https://github.com/mapzen/tile-tasks/issues/43.
=> Support storing individual formatted layers

tilequeue/command.py, tilequeue/process.py, tilequeue/worker.py
Connects to mapzen/tilequeue#70.
=> Pass context object to post-process functions.

CHANGELOG.md
@nvkelso could you review please?
=> Add changelog for v0.8.0

tilequeue/postgresql.py, tilequeue/process.py
=> Expand mz_properties in features

tilequeue/process.py
=> Exclude null values from yaml output

config.yaml.sample, tests/test_wof_http.py, tilequeue/command.py, tilequeue/wof.py
Connects to https://github.com/mapzen/vector-datasource/issues/654
=> Add boroughs to wof processing

tilequeue/postgresql.py
Connects to mapzen/vector-datasource#778.
=> Enable JSON extension.

tests/transform.py, tilequeue/wof.py
Connects to https://github.com/mapzen/vector-datasource/issues/418
Depends on https://github.com/mapzen/vector-datasource/pull/816
=> Add l10n_name to wof processing

tests/test_buffer.py, tilequeue/command.py, tilequeue/process.py, tilequeue/query.py, tilequeue/tile.py, tilequeue/transform.py
Connects to https://github.com/mapzen/vector-datasource/issues/106
=> Distinguish between meters per pixel area vs dim

tilequeue/process.py
Depends on https://github.com/mapzen/vector-datasource/pull/864
=> Remove simplification step (now a transform)

tests/test_store.py, tilequeue/store.py
Connects to https://github.com/tilezen/vector-datasource/issues/652
=> Support generating s3 urls with no path

tests/test_wof.py, tilequeue/wof.py
=> Treat empty strings as unknown dates

CHANGELOG.md, setup.py
Refs https://github.com/tilezen/vector-datasource/pull/920
@nvkelso could you review please?
=> Version bump -> v0.10.0

tilequeue/query.py, tilequeue/wof.py
Connects to https://github.com/tilezen/vector-datasource/issues/908
This should only get merged in once the hstore-all branch in vector-datasource does.
=> Update wof projection to 3857

tilequeue/worker.py
=> Extract size metadata from layers key

tilequeue/command.py, tilequeue/process.py, tilequeue/query.py
Refs https://github.com/tilezen/tilequeue/pull/106
This pulls in the changes from multiple-geometries-queries rebased onto master.
This should also demonstrate that there aren't additional test failures.
=> Support multiple geometries in queries

tests/test_store.py, tilequeue/store.py, tilequeue/worker.py
Connects to https://github.com/tilezen/tilequeue/issues/80
Only store the tile data if it's different from the existing data in the
store.
=> Conditionally store tile data

tests/test_wof.py, tilequeue/wof.py
Connects to https://github.com/tilezen/tilequeue/issues/110
Refs https://github.com/tilezen/vector-datasource/issues/976
=> Convert wof min/max zooms to floats

config.yaml.sample
Connects to https://github.com/tilezen/tilequeue/issues/93
@nvkelso, @zerebubuth, @iandees could you review please?
=> Update sample cfg to reflect latest choices

requirements.txt
=> Add pyclipper dependency to requirements

tilequeue/command.py, tilequeue/query.py
Add bbox filter to test for partial overlapping, rather than intersecting, the bbox.
=> Add bbox overlaps filter.

logging.conf.sample, tilequeue/command.py, tilequeue/tile.py
For https://github.com/mapzen/tile-tasks/issues/118
=> Add a command to dump the tiles of interest list to a text file

tilequeue/command.py
For https://github.com/tilezen/tilequeue/pull/120#discussion_r88032484
=> Don't use map during forloop while dumping TOI

tests/queue/test_multisqs.py, tilequeue/queue/multisqs.py, tilequeue/queue/sqs.py, tilequeue/tile.py, tilequeue/worker.py
Connects to https://github.com/tilezen/tilequeue/pull/133 (was ~~https://github.com/tilezen/vector-datasource/issues/1146~~)
=> Thread queue name through worker pipeline

tests/test_tile.py, tilequeue/tile.py
Connects to https://github.com/tilezen/tilequeue/issues/126
=> Update tile generator behavior

config.yaml.sample, tilequeue/command.py, tilequeue/config.py
Connects to https://github.com/tilezen/tilequeue/issues/127
=> Expose unique option for seeding

tilequeue/command.py
Connects to https://github.com/tilezen/tilequeue/issues/125
The seed command was realizing all coordinates in memory to print out the total count before enqueueing. This eliminates that and goes through an intermediary in-memory queue to keep the total memory footprint smaller.
=> Reduce tilequeue seed memory usage

tilequeue/postgresql.py
@zerebubuth, @iandees could you review please?
=> Update connection pool implementation

tilequeue/worker.py
The exception can propagate and kill this process, which blocks the queue and means that no more work is done by this worker! Ooops.
Also fixed up formatting of a comment which was annoying me.
cc @iandees, @rmarianski. I'm going to merge this now, but please let me know if you see a problem, or if there's an issue to follow up.
=> Handle an exception thrown when saving tiles.

tests/test_metatile.py, tilequeue/metatile.py
Added tests to make sure it's doing the right thing this time.
cc @iandees, @rmarianski. I'm going to merge this now, but please let me know if you see any problems or follow-up issues.
=> Fixed bug in parent tile calculation.

tilequeue/cache/redis_cache_index.py, tilequeue/command.py, tilequeue/utils.py
Another fix from https://github.com/tilezen/tilequeue/pull/180.
I was removing from the Redis TOI set when I should have been adding to it. Woops. 😬
=> Should have been adding to redis, not removing

tilequeue/command.py
=> Fix add/remove copy-paste error

tilequeue/command.py
From https://github.com/tilezen/tilequeue/pull/180
=> Limit the RedShift query to vector-tiles service

tilequeue/command.py
When we modify the tiles of interest set, generate some stats and emit them via statsd.
=> Output TOI stats by zoom to statsd

requirements.txt
Mirrors https://github.com/tilezen/tileserver/pull/101/files
=> Use pypi for mapbox-vector and edtf packages

tilequeue/process.py
Refs https://github.com/tilezen/vector-datasource/pull/1292
=> Create source metadata based on query results

config.yaml.sample, tests/test_process.py, tilequeue/command.py, tilequeue/config.py, tilequeue/process.py, tilequeue/utils.py, tilequeue/worker.py
Refs https://github.com/tilezen/vector-datasource/pull/1272
=> Move kind calculation to python

tests/test_process.py, tilequeue/process.py
Connects to https://github.com/tilezen/vector-datasource/pull/1362
=> Move min zoom check after yaml calculation

tilequeue/query/postgres.py
Connects to https://github.com/tilezen/vector-datasource/pull/1365
=> Support lists of templates per source

tilequeue/command.py
Having a command to process a single tile can be useful to reproduce
an issue on a dev instance.
Although this can be emulated by configuring a file based queue and
sticking the tile coordinate in there, having the ability to run
directly from the command line is easier.
=> Add a command to process a single tile

setup.py, tilequeue/command.py, tilequeue/rawr.py
The enqueueing and rawr tile generation is working for me locally. There's more that needs to be added to it, like error handling and logging, but I wanted to put this up for review first just to make sure the current implementation was adequate before spending effort on that. I was thinking that those kinds of improvements can be done in a subsequent pr.
=> Add rawr enqueue and process commands

logging.conf.sample, tilequeue/command.py, tilequeue/rawr.py, tilequeue/utils.py
=> Add logging to rawr commands

config.yaml.sample
=> Update sample config with rawr options

logging.conf.sample, tilequeue/command.py
* Remove intersect logging config
* Rename rawr_expiry -> rawr_enqueue
=> Update logging names

tilequeue/command.py, tilequeue/rawr.py, tilequeue/stats.py, tilequeue/worker.py
Updates processing metrics to send over in code now, instead of indirectly through logs via logstash.
Added new metrics for rawr tile enqueueing and generation.
=> Add stats handling

tilequeue/command.py
Connects to https://github.com/tilezen/tilequeue/pull/259#discussion_r145945432
=> Set default loglevel for loggers to INFO

logging.conf.sample, tilequeue/command.py, tilequeue/log.py, tilequeue/rawr.py, tilequeue/stats.py
=> Emit json from rawr processing logging

MANIFEST.in
Connects to https://github.com/tilezen/tileserver/issues/119
=> Include VERSION file in package

tilequeue/command.py, tilequeue/format/vtm.py, tilequeue/log.py, tilequeue/query/pool.py, tilequeue/query/postgres.py, tilequeue/rawr.py, tilequeue/wof.py
Connects to https://github.com/mapzen/tile-tasks/issues/302
=> Resolve new flake8 errors

tilequeue/rawr.py
=> Use underscore as the separator instead of dash

config.yaml.sample, tilequeue/command.py, tilequeue/rawr.py
=> Handle the case where the queue returns no msgs

tilequeue/log.py, tilequeue/rawr.py
=> Log when rawr processing starts/stops

tilequeue/command.py, tilequeue/rawr.py
=> Correct all calls to create rawr enqueuer's

tilequeue/query/__init__.py, tilequeue/queue/message.py, tilequeue/rawr.py, tilequeue/store.py, tilequeue/worker.py
=> Updates for tilequeue processing on dev

tilequeue/command.py, tilequeue/rawr.py
Depends on https://github.com/tilezen/raw_tiles/pull/12
Refs https://github.com/tilezen/raw_tiles/pull/11
=> Remove gzip rawr formatter

README.md
Add information about running `tilequeue` as well as testing and profiling it.
=> Add a running section to README.

config.yaml.sample, tests/queue/test_msg.py, tests/queue/test_sqs.py, tilequeue/command.py, tilequeue/log.py, tilequeue/queue/__init__.py, tilequeue/queue/file.py, tilequeue/queue/memory.py, tilequeue/queue/message.py, tilequeue/queue/redis_queue.py, tilequeue/queue/sqs.py, tilequeue/stats.py, tilequeue/utils.py, tilequeue/worker.py
There are some additional updates surrounding logging/stats here as well, as well as some fixes along the way.
=> Updates for sqs message visibility handling

tilequeue/log.py, tilequeue/queue/__init__.py, tilequeue/queue/message.py, tilequeue/queue/sqs.py, tilequeue/worker.py
=> Log additional details on msg ack errors

tilequeue/worker.py
Just something I randomly noticed.
=> Simplify _fetch_and_output function

tilequeue/command.py
=> Enqueue random samples to rawr queue

tilequeue/worker.py
=> Fix some errors in workers

tilequeue/log.py, tilequeue/worker.py
=> Log parent if available on fetch errors

config.yaml.sample, tilequeue/command.py
=> Add batch enqueue/process commands

tilequeue/command.py
This seeds all the tiles at the group-by zoom, which should be sufficient to generate all the RAWR tiles for a global build.
=> Add a tilequeue command to seed all the RAWR tiles.

config.yaml.sample, tilequeue/process.py
Related to https://github.com/tilezen/vector-datasource/pull/1489
=> Switch whosonfirst.mapzen.com to whosonfirst.org

tilequeue/command.py
Connects to https://github.com/tilezen/tileops/pull/3
=> Pass check-metatile-exists value on batch enqueue

config.yaml.sample, tests/test_rawr.py, tests/test_store.py, tilequeue/command.py, tilequeue/query/__init__.py, tilequeue/rawr.py, tilequeue/store.py, tilequeue/worker.py
This updates the rawr and metatile s3 paths. It:
* places the hex path prefix first
* removes the unused path and layer options
=> Update s3 paths

tilequeue/query/fixture.py
So that it matches the PostgreSQL query logic and RAWR tile processing logic. Both of these would allocate a name to a feature in a layer based on whether or not it has a non-NULL `min_zoom` for that layer, but the fixture was looking only at features visible at the current zoom. For example, that meant that if the YAML for a POI `min_zoom` was 16 and the `min_zoom` for landuse was 14, then the landuse layer would contain a label placement point at zooms 14 and 15.
The problem was that the fixture code was only looking at the assigned properties, and properties are only assigned if the feature's `min_zoom` is in the current range. I've added a `set` which tracks the layer names that assign the feature a `min_zoom`, and use that instead of only looking at properties.
=> Fix fixture name allocation logic

tilequeue/wof.py
Also add convenience interface for writing WOF neighbourhoods SQL to file.
```
>>> import timeit
>>> timeit.timeit('parse_edtf("uuuu")', setup='from edtf import parse_edtf', number=1000)
16.14653778076172
```
At 16ms per item, parsing 90,000 neighbourhoods is going to take about 24 minutes. Having fixed this, the parsing takes about 90s.
The reason this works is that the EDTF parsing seems a little slow, but 99+% of the input is `uuuu`, so we can special-case that to a fixed value which basically takes about zero time.
=> Special case parse for EDTF 'uuuu', massive increase in speed. 

tilequeue/wof.py
Parse Wikidata concordances for WOF records and store the result in the database. Used as part of tilezen/vector-datasource#858 to export wikidata IDs in the output tiles for WOF neighbourhoods.
Connects to tilezen/vector-datasource#858.
=> Add Wikidata ID to WOF records.

.flake8, tilequeue/command.py, tilequeue/config.py, tilequeue/store.py
Add more verbose log for low zoom tile build
also fix bunch of flake8 linter issues.
also add flake8 config file.
=> add more verbose log for low zoom tile build

tilequeue/command.py, tilequeue/config.py
We added support to assume the IAM roles in https://github.com/tilezen/tilequeue/pull/391, however for rawr tiles, some extra configs still need to be made, thus this PR.
=> Add config override for rawr build

tilequeue/utils.py
remove session refresher logs since it produces too many logs.
=> remove session refresher logs

.pre-commit-config.yaml, CHANGELOG.md
and fill out v2.4.1 notes with more details
=> Add v2.5.0 changelog
